/**
 * dsh-terminal build script.
 *
 * Host half:  esbuild bundles src/index.ts -> lib/index.js (ESM, node).
 *              node-pty / ws / @deepseek-ai/dsh-settings stay external
 *              (resolved by the dsh host at runtime); schemastery is bundled.
 * Client half: esbuild bundles src/client/index.ts -> CJS, then wraps it in
 *              the dsh web ModuleLoader contract:
 *
 *                  window.__ModuleLoader__.load({
 *                    id: "<pkg>",
 *                    factory: (require) => { ...; return module.exports; }
 *                  });
 *
 *              React / react-dom / react-dom/client / react/jsx-runtime stay
 *              external — platform seed words, the ONLY entities the shell
 *              shares into the frozen module table. @xterm/* is BUNDLED inline
 *              (matching the reference dsh-ssh plugin): the platform seed
 *              table has no xterm entry and the boot graph carries no row for
 *              it, so an external require would miss the module table at boot.
 *
 * xterm.css is embedded as a string module (src/client/xterm-css.ts,
 * generated) because the ModuleLoader environment has no CSS loader.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const src = join(root, 'src')
const lib = join(root, 'lib')
const tmp = join(root, '.build-tmp')

const PKG_ID = 'dsh-web-terminal'

rmSync(lib, { recursive: true, force: true })
rmSync(tmp, { recursive: true, force: true })
mkdirSync(lib, { recursive: true })
mkdirSync(tmp, { recursive: true })

// --- embed xterm css ---------------------------------------------------------
const xtermCss = readFileSync(join(root, 'node_modules/@xterm/xterm/css/xterm.css'), 'utf8')
const xtermCssModule = [
  '// AUTO-GENERATED by scripts/build.mjs — xterm.css embedded as a string for the ModuleLoader environment.',
  'export const XTERM_CSS: string = ' + JSON.stringify(xtermCss),
  '',
].join('\n')
writeFileSync(join(src, 'client/xterm-css.ts'), xtermCssModule)

// --- host bundle -------------------------------------------------------------
await esbuild.build({
  entryPoints: [join(src, 'index.ts')],
  bundle: true,
  outfile: join(lib, 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: true,
  external: ['node-pty', 'ws', '@deepseek-ai/dsh-settings'],
  logLevel: 'info',
})

// --- client bundle -----------------------------------------------------------
const clientTmp = join(tmp, 'client.cjs')
await esbuild.build({
  entryPoints: [join(src, 'client/index.ts')],
  bundle: true,
  outfile: clientTmp,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  jsx: 'automatic',
  sourcemap: false,
  external: [
    'react', 'react-dom', 'react-dom/client', 'react/jsx-runtime',
    '@deepseek-ai/dsh-client-runtime',
  ],
  logLevel: 'info',
})

// --- purity gate -------------------------------------------------------------
// The ModuleLoader's synchronous require can only resolve the platform seed
// words (the frozen table in @deepseek-ai/dsh-client-web). Anything else that
// survives as an external require in this bundle misses the module table at
// boot ("build-time externals drift"). Fail the build here instead.
const body = readFileSync(clientTmp, 'utf8')
const SEED_WORDS = new Set([
  'react', 'react-dom', 'react-dom/client', 'react/jsx-runtime',
])
const leaked = [...body.matchAll(/require\("([^"]+)"\)/g)]
  .map((match) => match[1])
  .filter((spec) => !SEED_WORDS.has(spec))
if (leaked.length > 0) {
  throw new Error(
    'client bundle would miss the module table at boot; external requires outside the platform seed words:\n' +
    leaked.map((spec) => `  - ${spec}`).join('\n') +
    '\nFix: bundle it inline (like @xterm/*), or for @deepseek-ai/* value imports add the package to dsh.client.inject.',
  )
}
const wrapped = [
  'window.__ModuleLoader__.load({',
  '\tid: ' + JSON.stringify(PKG_ID) + ',',
  '\tfactory: (require) => {',
  '\t\tvar module = { exports: {} };',
  '\t\tvar exports = module.exports;',
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  body.trimEnd(),
  '\t\treturn module.exports;',
  '\t}',
  '});',
  '',
].join('\n')
writeFileSync(join(lib, 'client.js'), wrapped)

rmSync(tmp, { recursive: true, force: true })
console.log('built lib/index.js + lib/client.js for ' + PKG_ID)